### ISSUE TITLE
Consider adding links to auto ML tools

### ISSUE THREAD

**Issue by rhiever** [ujjwalkarn/DataSciencePython#3]
Auto ML tools like [TPOT](https://github.com/rhiever/tpot) automate the process of designing machine learning pipelines for the user. Could be useful for newcomers to machine learning and data science. Could be worth adding to this list.

**Comment by ujjwalkarn** [comment]
Hey Randy, both this and OpenML.org are good suggestions, you can send me a pull request if you want, else I will add them myself.

**Comment by rhiever** [comment]
Please feel free to add them. :-)

**Comment by ujjwalkarn** [comment]
Added!
